spring:
  application:
    name: greeting-service

  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME:greeting_db}"
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

# Everything else comes from spring-boot-server defaults!


